spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://47.101.42.127:3306/comprehensive?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: lg20010922
mybatis-plus:
  configuration:
#    打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#   映射路径
  mapper-locations: classpath*:/mapper/*.xml
#   实体类别名
  type-aliases-package: com.goal.entity

